
service: crud-bucket-s3-aws

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless_ssm.yml)}
  apiGateway:
    apiKeys:
      - name : xApiKey
        value : ${file(./serverless_ssm.yml):X_API_KEY}
  logs:
    # Enable REST API logs
    restApi:
      accessLogging: true
      format: "requestId: $context.requestId"
      executionLogging: true
      level: INFO
      fullExecutionData: true
      role: arn:aws:iam::xxxx:role
      roleManagedExternally: false        
      

plugins:
  - serverless-s3-local
  - serverless-offline-ssm
  - serverless-offline

functions:
  uploadObject:
    handler: src/controllers/uploadObject.handler
    description: Function to store an object inside the s3 bucket
    events:
      - http:
          method: post
          path: /upload-object
          private: true        
  getObject:
    handler: src/controllers/getObject.handler
    description: Function to get an object from the s3 bucket
    events:
      - http:
          method: get
          path: /get-object/{uuid}
          private: true 
  editObject:
    handler: src/controllers/editObject.handler
    description: Function to edit an object from the s3 bucket
    events:
      - http:
          method: put
          path: /edit-object/{uuid}
          private: true 

resources:
  - ${file(src/resources/api-gateway.yml)}
  - ${file(src/resources/bucket-s3.yml)}

custom:
  s3:
    host: localhostdir
    directory: /tmp
  serverless-offline-ssm:
    stages:
      - dev
    ssm: 
      ${file(./serverless_ssm.yml)}    
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
