
service: crud-bucket-s3-aws

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(./serverless_ssm.yml)}
  apiGateway:
    apiKeys:
      - name : xApiKey
        value : ${file(./serverless_ssm.yml):X_API_KEY}
      

plugins:
  - serverless-s3-local
  - serverless-offline-ssm
  - serverless-offline

functions:
  debugBucketS3:
    handler : src/debug/bucketS3.handler
    events:
      - s3: local-bucket
        event: s3:*      
  uploadFile:
    handler: src/controllers/uploadFile.handler
    description: file storage in s3 bucket.
    events:
      - http:
          method: POST
          path: /dev/upload-file
          private: true        


resources:
  - ${file(src/resources/api-gateway.yml)}
  - ${file(src/resources/bucket-s3.yml)}

custom:
  s3:
    host: localhostdir
    directory: /tmp
  serverless-offline-ssm:
    stages:
      - dev
    ssm: 
      ${file(./serverless_ssm.yml)}    
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
